### ISSUE TITLE
What if stream and request-ID are in conflict?

### ISSUE THREAD

**Issue by huitema** [huitema/dnsoquic#10]
DNS over QUIC assumes that clients will pick a stream, say #3 for the first query with query ID = 1 and #5 for the second one with query ID = 2. It also assumes that the server response is sent back on the same stream over which the query was received. But what if the server is confused, and sends the response to query ID = 2 on stream #3, and the response to query ID = 1 on stream #5? What is the client supposed to do?

**Comment by huitema** [comment]
We need to consider the effect of RST-STREAM. Any of the parties can reset a stream at any time. We assume that this will cause the transaction to be abandoned: SERVFAIL if the server resets the stream, some client action if the client gives up on the transaction before it is fully complete. Having responses come on a different stream would not play well with that at all.

Proposal: clients shall verify that the query-id in the response matches the query-id that they sent in the query. If it doesn't, they should do something. But what? Probably too late to reset the stream, since it is now closed by both ends...

**Comment by janaiyengar** [comment]
On the first one: This is a "DNS over QUIC" protocol error, which IMO should cause the client to discard responses and close the QUIC connection. The client should also mark the server as "broken" for future use of DNS over QUIC.

**Comment by saradickinson** [comment]
In terms of matching section 6.4 already proposes using the same text as RFC7766 that clients MUST match on the QNAME, QCLASS, and QTYPE fields on a given stream. As for what to do if the match doesn't happen I think I agree with Jana that this is a bad enough error to back-off from the server.

**Comment by huitema** [comment]
Resolution: doq should use zero.

**Comment by huitema** [comment]
Specified in Dprive draft.
