### ISSUE TITLE
No mention of (mandatory) anti-replay

### ISSUE THREAD

**Issue by martinthomson** [huitema/dnsoquic#102]
Section 9.1 (Privacy Issues With 0-RTT data) talks about attackers being able to replay 0-RTT, but does not acknowledge the *mandatory* anti-replay techniques in RFC 8446.  This ends up being misleading.

For example:

> However, the risk is amplified for 0-RTT data, because the attacker might replay it at chosen times, several times.

This is not true.  If the time-based anti-replay techniques are deployed (which are mandatory and easy to implement), then an attacker cannot choose when to replay data.  They are only able to replay within a narrow window, which is only wide enough to account for variations in clock skew and network transmission.  This can be a fairly tight window depending on how willing you might be to reject 0-RTT if there is packet loss or relative clock drift.

**Comment by huitema** [comment]
Good catch. I will try to come up with some clarification.
