### ISSUE TITLE
Reference RFC 7830 instead of RFC8467

### ISSUE THREAD

**Issue by huitema** [huitema/dnsoquic#129]
Form: Alexander Mayrhofer <alex.mayrhofer.ietf@gmail.com>
Sara, Allison, Christian,

I read through the latest revision of DoQ, and i'm afraid i do have a
comment regarding the padding section. More specifically, i think the
second "option" of section 6.4 should refer to the base specification
of EDNS0-Padding, rather than the Padding policies RFC. It currently
reads as:

   *  if padding at the QUIC level is not available or not used, DNS
      over QUIC MUST ensure that all DNS queries and responses are
      padded to a small set of fixed sizes, using the EDNS padding
      extension as specified in "Padding Policies for Extension
      Mechanisms for DNS (EDNS(0))" [RFC8467].

And i do believe that - as the sentence stands - the reference should
be RFC 7830. Note that RFC 8467 is Experimental (and was by intent, as
the privacy properties of Padding would probably shift with more
operational expertise). So, i feel REQUIRING that padding is used
makes more sense than REQUIRING the use of the experimental padding
sizes in RFC8467.

I think the sentence should read "padded to a small set of fixed
sizes, using the EDNS Padding Extension as specified in [RFC7830]."

I like the "aligned with..." text in the previous bullet point, which
could also be used here, indicating that the MUST is for the the
padding, and not necessarily for that revision of the padding policy.

It's not a showstopper, though. What do you think?

best,

**Comment by saradickinson** [comment]
Addressed in -08
