### ISSUE TITLE
Zaheduzzaman Sarker's ballot comments

### ISSUE THREAD

**Issue by huitema** [huitema/dnsoquic#151]
Zaheduzzaman Sarker has entered the following ballot position for
draft-ietf-dprive-dnsoquic-10: No Objection

When responding, please keep the subject line intact and reply to all
email addresses included in the To and CC lines. (Feel free to cut this
introductory paragraph, however.)

Please refer to https://www.ietf.org/about/groups/iesg/statements/handling-ballot-positions/ 
for more information about how to handle DISCUSS and COMMENT positions.

The document, along with other ballot positions, can be found here:
https://datatracker.ietf.org/doc/draft-ietf-dprive-dnsoquic/

----------------------------------------------------------------------
COMMENT:
----------------------------------------------------------------------

Thanks a lot for working on this specification. Thanks to Brian Trammell  for
the TSVART review.

I have following comments and I think addressing them will improve this
documentation-

   * Section 5.3.3 - should also list the protocol error case related to 
   session resumption and 0-RTT, and put a reference to section 5.5 for further
   details.

   * Section 5.2 says -

     "Implementations MAY impose a limit on the number of such dangling
     streams. If limits are encountered, implementations MAY close the
     connection."

     However, I have  not notices any indication  of how this limits can be
     set. I would be great if we can say how the implementer can enforce the
     normative "MAY".

**Comment by saradickinson** [comment]
https://github.com/huitema/dnsoquic/pull/162 tries to address the first bullet, but I'm not sure what is being asked in the second? Is the answer 'by keeping state on each stream' or 'by adding a configuration option to define the limit'?

**Comment by huitema** [comment]
Session resumption comment is addressed in PR #162. Dangling streams comment is addressed in PR #161.
