### ISSUE TITLE
Do servers need a way to control the number of outstanding requests?

### ISSUE THREAD

**Issue by huitema** [huitema/dnsoquic#8]
The "one query per stream" architecture allows clients to open as many streams as they want, and thus submit as many outstanding requests as they want. Clients could in theory open a large number of streams and flood the server. 

The transport level flow control in QUIC provides some defense, but it only limits the number of outstanding packets. A single QUIC packet could carry many stream openings, so this is a blunt instrument. A server under stress could use RST-STREAM to perform the equivalent of dropping a packet in UDP over DNS. But then, this creates another issue: a good client may just be sending many requests for good reasons, and may start experiencing bad service due to streams being reset.

The client could pace itself by limiting the number of outstanding queries. But how does it know how much is enough and how much is too much?

**Comment by saradickinson** [comment]
At a quic glance the -02 quic draft, section 7.3.1 says:

 concurrent_streams (0x0002):  The maximum number of concurrent
      streams parameter is encoded as an unsigned 32-bit integer.

Which sounds useful :-)

More generally: 

One option is to include text such as 'servers may choose to implement a mechanism analogous to RLL", although obviously the TC bit wouldn't have the same meaning.

We could also create some text very similar to that in the Security Considerations section of RFC7766 that says servers should offer config options to allow limiting of lots of things (e.g. maximum DNS transactions per connection) but doesn't specify values: https://tools.ietf.org/html/rfc7766#page-12

Clients typically already track statistics for their upstreams and back-off when they get lots of 'timeouts/drops', this seems to be implementation dependant though but we could give some examples. Unbound and getdns clients have configuration options for the max number of outstanding queries. 

As always with DNS signalling capabilities is not easy.

**Comment by huitema** [comment]
OK. Should add text explaining how to use the stream limit to control the max number of incoming packets.

**Comment by huitema** [comment]
Text on stream limit was added to draft.
