### ISSUE TITLE
How do endpoints handle reception of unknown error codes?

### ISSUE THREAD

**Issue by LPardue** [huitema/dnsoquic#80]
This affects stream actions more than connection actions. But you should probably state what happens if an unknown code is received. I suggest it is treated as if DOQ_NO_ERROR was received.

**Comment by huitema** [comment]
I see where you are going. Application-level error codes can be received in:

* Reset Stream
* Stop Sending
* Connection Close by Application

The current draft specifies a few codes. New code points may be registered by revisions of the specification, or through IANA. 
In my mind, these codes are primarily there to aid debugging. That should not cause application misbehavior. 

Let's find a way to say that.

**Comment by huitema** [comment]
Please check PR #108, which should address this issue.

**Comment by huitema** [comment]
Resolved in PR #108
