### ISSUE TITLE
GREASEing of error codes

### ISSUE THREAD

**Issue by LPardue** [huitema/dnsoquic#81]
Your error codes are an extension point that isn't being exercised. In HTTP/3 we GREASE all extension points like error codes to avoid ossification. Something to consider here too.

**Comment by martinthomson** [comment]
I would reserve far fewer codepoints than we did in QUIC.  It turns out to be a bit of a nuisance to have them so densely distributed throughout the space.  DNS probably won't end up with the same problems, but it doesn't need to make that mistake too.

**Comment by martinthomson** [comment]
No one is forcing you to take the most extreme interpretation :)  I'm sure whatever you decide will take the various considerations into account.

I believe that you need to grease that way, yes.  In HTTP at least we have plenty of cases where we send error codes.  DNS might not, but you might imagine abandoning a query.  Zone transfers might need to be cut off too.

**Comment by huitema** [comment]
I suppose that the client can send a query for "www.,example.com", then immediately cancel it, easier with the expect code or with a grease value. Only downside is hitting the DNS server of example.com with extra traffic. OK, maybe we could just hit "grease.cloudflare.com", since this was Lucas' idea...

**Comment by LPardue** [comment]
How about grease.grease.grease.grease.one.one.one.one?

**Comment by huitema** [comment]
Depends on the recursive resolver. If it does NSEC3 aggressive caching, then fine. But a good share of resolvers don't, and the request for ".one" just hits the root. That kind of stuff is about half of the root traffic. I am definitely not writing that in an RFC.

**Comment by huitema** [comment]
Greasing indeed. sending a stop sending to the server before it has a chance to start sending...

**Comment by huitema** [comment]
Resolved by PR #108
