### ISSUE TITLE
Port 953 may be in use already by BIND tool RDNC

### ISSUE THREAD

**Issue by huitema** [huitema/dnsoquic#9]
Just got this from michiel@klaver.it, on 4/11/2017:

Hi Christian,

I've read draft-huitema-quic-dnsoquic-00 and noticed section 9.2 is requesting a reservation for port 953. To my knowledge, that one is already in use by DNS Bind tool 'rndc' and could be a possible conflict.

As that is a default (changeable) Bind config and not official registered port, I guess a notice would suffice.

Best regards,
Michiel Klaver

**Comment by saradickinson** [comment]
I believe Ray Bellis is asking for a port assignment for this: 


> On 11/04/2017 12:28, Marco Davids (IETF IMAP) wrote:

> I see why port 953 was chosen. But it is also a longtime de facto
> default for the rndc communications channel of BIND.

Yes, it is.

I am trying to make that formal rather than de facto with IANA at the
moment.

Ray
