### ISSUE TITLE
DSO carveout

### ISSUE THREAD

**Issue by martinthomson** [huitema/dnsoquic#91]
I think that not supporting DSO was entirely a choice on the part of the authors.  An extension could be defined that would make DSO possible.  There are some interesting questions to answer there (particularly around the use of authentication and how reference identities are used), which is why I support keeping it out of scope.  However, this is NOT the same as HTTP in that this entirely new protocol is not prevent by existing constraints from adding this communication mode; it is merely a choice.

On that basis, I would suggest that the following be amended:

> [...] DSO is not applicable to DNS over HTTP since HTTP has its own mechanism for managing sessions, and this is incompatible with the DSO; the same is true for DoQ.

(That sentence is already a run-on, by the way.)

I would suggest something like:

> This definition of DoQ does not include support for DSO.

And maybe also:

> A revision or extension to this specification might define the use of DSO with DoQ.

**Comment by huitema** [comment]
Yes, this seems fine. Removing the discussion of HTTP is a good idea. Supporting DSO appears simple, we would "just" have to let the server open streams and push transactions on them, but it has interesting interactions with connection management, NAT rebinding, keep alive, etc. So yes, it is "a choice on the part of the authors". @saradickinson, do you have a strong opinion?
