### ISSUE TITLE
XFR and 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [huitema/dnsoquic#99]
I think that this is incorrect:

> For the zone transfer scenario, it would be possible to replay an XFR QUERY that had been sent in 0-RTT data. However the authentication mechanisms described in RFC9103 ("Zone transfer over TLS") will ensure that the response is not sent by the primary until the identity of the secondary has been verified i.e. the first behavior listed above.

If mutual authentication is used on an original connection, a subsequent connection can use 0-RTT and retain all authentication information.  This means that XFR could be initiated in 0-RTT.

Furthermore, replay protections depend on the server not *doing* anything with what was in the 0-RTT request.  I don't know whether XFR might result in actions that are non-idempotent or unsafe (using HTTP terms here for lack of better - maybe "without side effects" is better).  If something does happen, then the condition you rely on does not hold.

It might be better to remove this text and rely on the generic advice.

**Comment by huitema** [comment]
Maybe. There is probably no urgent requirement to support 0-RTT for XFR. @saradickinson, any strong opinion?

**Comment by huitema** [comment]
I think PR #114 fixed this issue. Can we close it?
